### ISSUE TITLE
Баг в практической реализации ценности "Ставить потребности пользователей на первое место"

### ISSUE THREAD

**Issue by borouhin** [avito-tech/playbook#2]
Дано:

1. Заявлена как первая ценность "Ставить потребности пользователей на первое место.": 
> "Главная наша задача — **делать наших конечных пользователей счастливее,** предоставляя им необходимые продукты или помогая коллегам в их запуске и поддержке. Мы **прислушиваемся к мнению пользователей** и стараемся делать по-настоящему полезные продукты".

2. Я являюсь конечным пользователем, который должен быть облагодетельствован в соответствии с описанным в п. 1.

3. Некоторое время назад обнаружил, что доступ к сервису с IP-адреса моего личного (никем более не используемого) VPN-сервера заблокирован. Обратился в поддержку (тикет 10616859), получил ответ, что заблокирована вся подсеть AWS из-за того, что с неё осуществлялся автоматический парсинг, и исправлено это не будет.

4. Таким образом, доступность сервиса для конечного пользователя и учёт его мнения поставлены ниже, чем простота борьбы с конкурентами в стиле Роскомнадзора (ну или небезысвестного инквизитора, призвавшего "Убивайте всех, Господь распознает своих"). Налицо нарушение базовой ценности, прошу пофиксить.

**Comment by toogle** [comment]
@borouhin, мы боремся с парсингом и спамом не по своей прихоти, а дабы обезопасить наших пользователей от их вредной активности. И в этой борьбе наши ресурсы, увы, ограничены. Поэтому мы приняли решение заблокировать VPS- и cloud-хостинги, исходя из предположения, что "живых" пользователей там быть не должно, а если они есть, то прекрасно осознают последствия и возможные ограничения, а также знают пути разрешения этой проблемы (навскидку, отключить VPN или настроить маршрутизацию к Авито в обход туннеля). Не вижу здесь противоречия с нашими ценностями.

**Comment by borouhin** [comment]
Есть подозрение, что скоро там окажется 100% живых пользователей, оснащённых достаточным для этого количеством мозгов. И перекладывание Ваших технических проблем _(детектить парсеры индивидуально по количеству / частоте / паттернам запросов - конечно, непосильная для такой крупной компании задача)_ на пользователей - это и есть нарушение продеклирированной Вами ценности.
Ну и вообще, ковровые блокировки после того, как их принял на вооружение РКН, стали безусловным моветоном в приличном обществе. Даже если раньше можно было рассуждать о допустимости таких мер - теперь прибегающим к ним не подают руки. Просто чтобы не уподобляться.
