### ISSUE TITLE
Ссылка на OTUS курс 'Data scientist' устарела

### ISSUE THREAD

**Issue by EvilKhaosKat** [avito-tech/playbook#20]
https://github.com/avito-tech/playbook/blob/master/students.md упоминает курс `Data Scientist`, но ссылка устарела.
Увы неочевидно какой курс имелся ввиду, иначе можно было бы сразу сделать пулл реквест :)

**Comment by oldtuna** [comment]
Спасибо, поправили! Курс сменил название на Machine Learning :)
