### ISSUE TITLE
На странице Open-source нарушен баланс в представлении деятельности Avito в Open Source'е

### ISSUE THREAD

**Issue by artyom-razinov** [avito-tech/playbook#3]
Шаги:

1. Зайти на https://github.com/avito-tech/playbook/blob/master/avito-open-source.md
2. Совершить первый взгляд на страницу.

Актуальный результат:

3. На первый взгляд кажется, что Avito от своего имени ничего не выпускает. В глаза бросается куча проектов не из организации avito-tech

Ожидаемый результат:

3. В глаза бросается упоминание о проектах, которые лежат в этом репозитории.

Думаю, следует как минимум описать самые звездные проекты. Как-то сбалансировать проекты от имени Авито и от имени сотрудников

**Comment by etolstoy** [comment]
@oldtuna Миша, что думаешь? Я за то, чтобы все упомянуть – иначе правда складывается впечатление, что это все, что мы делаем.

**Comment by oldtuna** [comment]
Я только за, давайте дополним этот раздел

**Comment by oldtuna** [comment]
Сделал списочек там, кроме Донера и Конвеера добавил всё, что было из нашего
