### ISSUE TITLE
Неоднозначность в определении для Bitbucket

### ISSUE THREAD

**Issue by h4** [avito-tech/playbook#4]
В разделе [Процессы и стандарты](https://github.com/avito-tech/playbook/blob/master/processes-and-standards.md) в секции «Инструменты» указано:

> VCS — Bitbucket

К сожалению, в голове у многих разработчиков прочно засела соотношение Bitbucket == Mercurial. Кроме того, Bitbucket — это не система хранения версий (простите за буквоедство).

Мне кажется, что можно значительно снизить число потенциальных вопросов, если переписать эту строчку примерно в таком ключе:

> VCS-хостинг — Bitbucket (git)

**Comment by etolstoy** [comment]
Спасибо, поправили!
