### ISSUE TITLE
Недосказанность в structure.md

### ISSUE THREAD

**Issue by AleximusOn** [avito-tech/playbook#7]
Страница [structure.md](https://github.com/avito-tech/playbook/blob/master/structure.md)
Текст:

> Состав команды в основном определяется ее направлением деятельности. Чаще всего они формируются вокруг реализации какой-то потребности пользователя, либо вокруг определенной части сервиса. Пара примеров.
> 
> - Коллеги из юнита Messenger, как можно догадаться из названия, разрабатывают всё, что связано с нашим мессенджером.
> 
> - Юнит TechPR организует митапы, помогает докладчикам готовить доклады, публикует статьи на Хабре и так далее.

Ожидается что в примерах будет описан состав команд юнита Messenger и юнита TechPR, с пояснением почему в юните TechPR красивые, а в юнита Messenger - умные, к примеру

**Comment by oldtuna** [comment]
Уточнил структуру юнитов из примера.
